adicionando rota de patrocionador
MintzyG/SCTI pull request #116
Opened 2024-09-04 01:36 UTC by JuliannaRkg544

2024-09-04 17:22 UTC, MintzyG requested changes

2024-09-04 17:22 UTC, MintzyG commented on src/database/db.go
A indentação mudou do arquivo inteiro de novo ;-;

2024-09-04 17:22 UTC, MintzyG commented on src/database/db.go
> -  err := DB.QueryRow(query, uuid).Scan(&isPaid)
O que aconteceu com o arquivo db?
Essas funções são críticas, vê se você deu pull certinho e se não ta faltando nada disso no seu código

2024-09-04 17:22 UTC, MintzyG commented on src/rotas/patrocinadores/handler.go
> +	}
Isso não é necessario, todas as rotas inválidas são pegadas pelo catch all na rota home

2024-09-04 17:22 UTC, MintzyG commented on src/rotas/patrocinadores/handler.go
> +	}
O arquivo gohtml dessa rota não está sendo declarado com: 
{{ define "patrocinadores" }} conteudo {{ end }}
Logo não pode ser servido por essa lógica,deve ser servido por:
```go
  var t = fileserver.Execute("template/patrocinadores.gohtml")
  t.Execute(w, nil)
```

2024-09-04 17:22 UTC, MintzyG commented on src/rotas/patrocinadores/handler.go
> +	mux.HandleFunc("/patrocionadores", GetPatrocionadores)
Tipo de rota não foi especificado

```go
'mux.HandleFunc("GET /patrocionadores", GetPatrocionadores)
```

2024-09-04 17:22 UTC, MintzyG commented on src/template/patrocionadores.gohtml
> +</html>
Caso não queira mudar o jeito que o arquivo está servido pelo backend coloque neste arquivo
```gohtml
{{ define "patrocinadores" }}
  Conteudo atual
{{ end }}
```

2024-09-04 20:47 UTC, JuliannaRkg544 commented on src/rotas/patrocinadores/handler.go
> +	}
alterado

2024-09-04 20:49 UTC, JuliannaRkg544 commented on src/database/db.go
> -  err := DB.QueryRow(query, uuid).Scan(&isPaid)
acredito ter corrigido agr :/

2024-09-05 15:54 UTC, MintzyG approved these changes

2024-09-05 15:54 UTC, merged