Fix/dashboard payment
MintzyG/SCTI pull request #154
Opened 2024-09-26 00:29 UTC by juanzeen

# PR de emergência

## Fiz

Alinhei os botões da dashboard mais a direita, com um pequeno gap de 16px para que não ficasse muito separado entre eles. A página não possui responsividade própria, está funcionando com base no zoom.

Além disso, consertei a quebra de texto do copia e cola, mas ainda não consegui fazer o botão para copiar.

## Resultados 

https://drive.google.com/file/d/1uqvAew9g6NZ_KpCqH5IU4_px9_n2yXg5/view?usp=sharing

2024-09-26 01:00 UTC, MintzyG requested changes
Verifica se a sua branch está atualizada corretamente, muda essa PR pra fazer merge na branch milestone

2024-09-26 01:04 UTC, juanzeen commented on src/template/dashboard.gohtml
Olhei pra sua branch ao invés do meu fork, to revendo as alterações aqui e coloquei como draft

2024-09-26 01:19 UTC, JuliannaRkg544 approved these changes

2024-09-26 02:55 UTC, SoraAsc approved these changes

2024-09-26 03:36 UTC, MintzyG commented
Olha me parece que ainda está a regressão, tenta merge da production pra tua e ve se vai, tbm muda esse PR pra fazer merge na milestone e ve se some

2024-09-26 03:38 UTC, juanzeen commented
Amanhã de manhã finalizo isso, troco a branch de comparação e faço o merge resolvendo possíveis conflitos

2024-09-26 16:56 UTC, juanzeen commented
@MintzyG @EmanuelPeixoto verifiquem por favor se eu não fiz merda

2024-09-27 02:43 UTC, MintzyG approved these changes

2024-09-27 02:43 UTC, merged